import Head from "next/head";
import styles from "../styles/Home.module.css";

// NextUI
import { Text, Tooltip } from "@nextui-org/react";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next UI</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Text
          h1
          size={60}
          css={{
            textGradient: "45deg, $blue500 -20%, $pink500 50%",
          }}
          weight="bold"
        >
          Let&apos;s
        </Text>
        <Text
          h1
          size={60}
          css={{
            textGradient: "45deg, $purple500 -20%, $pink500 100%",
          }}
          weight="bold"
        >
          Make the Web
        </Text>
        <Text
          h1
          size={60}
          css={{
            textGradient: "45deg, $yellow500 -20%, $red500 100%",
          }}
          weight="bold"
        >
          Prettier
        </Text>

        <Tooltip content={'We are really out there'} color='error' placement='bottom'>
          <h1 className={styles.title}>
            We are putting the love back in the game
          </h1>
        </Tooltip>
      </main>
    </div>
  );
}
